# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
# Trouble Shooting:
# https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#config-file-error

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
extensions: [fenced_code_blocks]
excerpt_separator: "<!--more-->"

colors: 
  main: e23021


# Site Company
title: Matter Voting
tagline: Currency with a Material Feel.
company:
  name: Matter Voting
  site: https://github.com/Matter Voting
  description: Crypto Wallets.
  image: social-image.png
  email: 'contact@Matter Voting.com'
  # social medias:
  linkedin:   company/Matter Voting
  twitter:    FiMatter
  facebook:   Matter Voting-108207714429114/s
  instagram:  Matter Votingnance
  github:     Matter Voting
  telegram:   Matter Voting
  discord:    RVGfCbZNmG
  pinterest:  null
  feedburner: null


# Company Contact Information in one place:
# {{ site.contact_info.<item> }}
contact_info:
  address_ln1: 30 N Gould St, Ste 400
  address_ln2: Sheridan, WY 82801
  phone: Phone#
  email: contact@Matter Voting.com

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url: https://www.Matter Voting.com
url: https://Matter Voting.github.io
baseurl: ""

# Used when creating press post html pages from markup:
# Press Release posts are located in the _posts directory and are markdown style.
# Read more about formatting here:
# https://heliumjk.github.io/docs/2017/10/08/helium-jekyll-theme-markdown-examples
permalink: /:categories/:year/:month/:day/:title
highlighter: null
markdown: kramdown

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
#google_ad_client: ca-pub-9204963049240271
#data-ad-client: ca-pub-9204963049240271
#data-ad-slot: 2973388149

# Counts
counts:
  downloads: 561
  # (unix: git ls-files | xargs wc -l)
  # (windows powershell: dir -Recurse -Include *.ts,*.tsx -Exclude *node_modules* | Get-Content | Measure-Object -Line)
  code_lines: 459,861
  # https://github.com/Open-Transactions/opentxs
  commits: 5,844
  # https://github.com/Open-Transactions/opentxs/graphs/contributors
  contributors: 29

# Team Information
team:
  member_01:
    name: Tim Rocho
    title: CEO
    catchphrase: Great Ideas are plentiful, its execution that really Matters.
    background: 'Relentlessly focus on customer needs and you may be successful.'
    twitter: null
    instagram: null
    facebook: null
    linkedin: https://www.linkedin.com/in/timrocho/
  member_02:
    name: Mehow Powers
    title: President
    catchphrase: "Theft and fraud don’t have to be possible."
    background: "When I was younger I worked as a consultant hacking corporate machines, if you think your electronics and financial systems are secure, do I have news for you. Now I’m building technology that eliminates theft and fraud so that these issues can never happen again."
    twitter: null
    instagram: null
    facebook: null 
    linkedin: https://www.linkedin.com/in/michal-mehow-pospieszalski-1b3b4443/
  member_03:
    name: Chris Odom
    title: Technology Founder
    catchphrase: When I wrote Open Transactions in 2010 it was too early, now I know it’s the right time.
    background: 'Bitcoin was released in 2009, I wrote open transactions as a response to bitcoin in 2010.'
    twitter: null
    instagram: null
    facebook: null
    linkedin: https://www.linkedin.com/in/chris-odom-257236/

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB:
  version: 0.3.0

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.io)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.io/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  #https://Matter Voting.github.io
  BASE_PATH: false

  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #
  analytics:
    provider: google

    google:
      tracking_id: 'G-8BPS3KCJ4L'

  #  getclicky:
  #    site_id:

  #  mixpanel:
  #    token: '_MIXPANEL_TOKEN_'

  #  piwik:
  #    baseURL: 'myserver.tld/piwik' # Piwik installation address (without protocol)
  #    idsite: '1'                   # the id of the site on Piwik

  # Settings for sharing helper.
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing:
    provider: false
